### ISSUE TITLE
Decorate with auto-typing code snippets

### ISSUE THREAD

**Issue by rashil2000** [ScoopInstaller/scoopinstaller.github.io#24]
_From @JanPokorny in #10:_

> A text field/widget that has the text `> scoop install something` where "something" is animated -- periodically deleted and retyped as if user was typing, showing an assorted selection of tools one might want to install through scoop -- this draws attention and quickly shows what scoop does. (I've seen some corporate websites use this kind of animation, seems pretty suited here) -- similar to the result of this snippet https://stackoverflow.com/a/32496921/6099426

> This website can be used as reference: https://www.localsolver.com/

_From @gpailler in #10:_

> I found [react-code-auto-typing](https://www.npmjs.com/package/react-code-auto-typing) that could probably do the job

**Comment by gpailler** [comment]
Thanks for the idea. asciinema looks very promising !
There is a highly [customizable player](https://github.com/asciinema/asciinema-player#use-the-player-in-your-own-application-bundle) that we can integrate and a Powershell recorder [powersession-rs](https://github.com/Watfaq/PowerSession-rs) (available on scoop 😄  )

**Comment by sitiom** [comment]
> There is a highly [customizable player](https://github.com/asciinema/asciinema-player#use-the-player-in-your-own-application-bundle) that we can integrate and a Powershell recorder [powersession-rs](https://github.com/Watfaq/PowerSession-rs) (available on scoop 😄 )

"Powershell" recorder might be a misnomer since it doesn't just work only in Powershell 😅

**Comment by gpailler** [comment]
> "Powershell" recorder might be a misnomer since it doesn't just work only in Powershell 😅

Yes very true, I meant a Windows recorder 😅

**Comment by gpailler** [comment]
I have integrated asciinema-player, available on https://scoop.sh/scoopinstaller-dev.github.io/ for the installation examples.

What are your thoughts, should we use asciinema-player in other places, like the scoop search section ?

**Comment by sitiom** [comment]
Looks great! I suggest using it in the other sections for consistency.

**Comment by JanPokorny** [comment]
This solution seems to solve a different problem than I originally meant (I wanted to quickly explain to the user what an "app" means in this context, by showing examples next to the search field), but I must say that the animations look pretty

**Comment by gpailler** [comment]
I have a quick survey for you @sitiom @JanPokorny @rashil2000 

Could you check https://scoop.sh/scoopinstaller-dev.github.io/ once again and tell me what do you prefer between the following options:
- Node.js => No loop, controls not displayed
- NeoVim => Loop, controls not displayed
- VS Code => No loop, controls displayed
- Cascadia-Code => Loop, controls displayed

I would choose loop without controls or no loop with controls but I'm interested in your feedback.

Thanks!

**Comment by JanPokorny** [comment]
IMO no loop no controls is best, it looks cool and it lets you read the whole output in peace at the end

**Comment by sitiom** [comment]
I'm going for loop and controls. One can pause at any point the user wants to. Maybe we can host a poll for this:
[![](https://api.gh-polls.com/poll/01G725PHZ6DKHXP31NF9X25QJE/No%20loop%2C%20No%20Controls)](https://api.gh-polls.com/poll/01G725PHZ6DKHXP31NF9X25QJE/No%20loop%2C%20No%20Controls/vote)
[![](https://api.gh-polls.com/poll/01G725PHZ6DKHXP31NF9X25QJE/Loop%2C%20No%20Controls)](https://api.gh-polls.com/poll/01G725PHZ6DKHXP31NF9X25QJE/Loop%2C%20No%20Controls/vote)
[![](https://api.gh-polls.com/poll/01G725PHZ6DKHXP31NF9X25QJE/No%20loop%2C%20Controls)](https://api.gh-polls.com/poll/01G725PHZ6DKHXP31NF9X25QJE/No%20loop%2C%20Controls/vote)
[![](https://api.gh-polls.com/poll/01G725PHZ6DKHXP31NF9X25QJE/Loop%2C%20Controls)](https://api.gh-polls.com/poll/01G725PHZ6DKHXP31NF9X25QJE/Loop%2C%20Controls/vote)

**Comment by rashil2000** [comment]
I've voted for the no loop, no controls option, but I'm not a big fan of the embed being dark themed when the background is light. Technically it should be possible to toggle the asciinema-player theme along with site theme, no?

**Comment by sitiom** [comment]
> I've voted for the no loop, no controls option, but I'm not a big fan of the embed being dark themed when the background is light. Technically it should be possible to toggle the asciinema-player theme along with site theme, no?

It would just require a [`theme`](https://github.com/asciinema/asciinema-player#theme) change.
