### ISSUE TITLE
Opinion: "Official buckets only" filter should be on by default

### ISSUE THREAD

**Issue by mertd** [ScoopInstaller/scoopinstaller.github.io#26]
Hi! Congratulations on getting the new scoop.sh website and search online. Looks great!

Since this is the official scoop web search now, I think the "Official buckets only" filter should be on by default. Displaying additional buckets is great for advanced users. For new users of Scoop or package managers in general, however, it introduces additional complexity and may even leave their systems vulnerable because they installed code from weakly moderated buckets.

What do you think? @gpailler @rashil2000

**Comment by rashil2000** [comment]
That's something I have considered before (I personally prefer it), but a big disadvantage would be that it will hamper discoverability: most users might never get to know that there are community buckets out there too.

**Comment by gpailler** [comment]
Yes, I remember it was heavily discussed 😉
I personally think it's one of the strength of Scoop to propose community/unofficial buckets and it would be a pity to hide them by default. 
One improvement could be to make this filter more discoverable (not hidden in the Sorting/Filtering menu) but we were not able to find the right spot. We tried different positions but it was always making the web page "unbalanced" and the result was not very nice. New ideas are welcome though !

When using the "Best match" sorting (the default one), the results from official buckets/popular community buckets are returned first so I'm not sure it's really disturbing for the users. We are supposed to always propose "safe" results first.

**Comment by rashil2000** [comment]
One idea that was discussed in the original issue #1 was to put the toggle in center below the search bar, with the text "Search only known buckets" and the toggle enabled by default. It does look distracting as @gpailler mentioned but it also lets users know that there are other buckets too.

**Comment by mertd** [comment]
I agree that the toggle should be more prominent once turned off as a default. I personally actually like the direction of what seems to have been the [first design iteration](https://github.com/ScoopInstaller/scoopinstaller.github.io/issues/1#issuecomment-1013696200). At the same time, the current state does look more polished.

What do you think about displaying the current sort and filter settings on the button label? E.g. "Official buckets only" and "All buckets", or "Community buckets excluded" and "Community buckets included".

Examples:

![grafik](https://user-images.githubusercontent.com/7928036/169645710-e44f5d27-d829-4c82-bb4a-8fc96fbbb284.png)

![grafik](https://user-images.githubusercontent.com/7928036/169645825-e83361e8-b6dd-4102-a146-eb7a65ed8e54.png)

This would highlight the option to display more buckets to users once showing only the official ones as default. Saving these settings in local storage may also be of help to users who want the community buckets included.

**Comment by mertd** [comment]
Another option could be to leave the default as-is, but overlay the installation command fields. The overlay could be a message briefly explaining the benefits and risks of community buckets. Alternatively, the actual text could be in a modal and the overlay could just contain a "Display instructions" button. Once dismissed via a button that says something along the lines of "I understand, do not warn me again", the display state could be stored to local storage.

This would allow displaying all buckets as standard, but require more time to implement and may disturb the current polish of the design. Therefore, I prefer my [first suggestion](https://github.com/ScoopInstaller/scoopinstaller.github.io/issues/26#issuecomment-1133590536) over this.

**Comment by gpailler** [comment]
Hello @mertd,
It's a great idea to use the dropdown title to display the current sort and filter!
On https://scoop.sh/scoopinstaller-dev.github.io/#/apps, you will find this idea implemented:
- Current sort and filter are displayed on the dropdown title
- Official buckets filter is enabled by default
- Current sort and filter are stored in local storage and are used if not specified in the URL

(I'm still not 100% convinced that we should filter out the community buckets by default. ~18500 apps is more appealing than ~4200 for a first time user, even if we have duplicates)

What are your thoughts?

**Comment by mertd** [comment]
@gpailler This version looks great!

I believe that scoop has its own place due to a few unique qualities rather than app count. That being said, I understand your concern of appealing to first-time users. How do you feel about always showing both the current result count as well as the total number of apps?

Examples:

![grafik](https://user-images.githubusercontent.com/7928036/169791430-ddf38ab7-46a5-42c0-9e9a-1218d8b76ca2.png)

![grafik](https://user-images.githubusercontent.com/7928036/169791576-75104662-0a6a-42b3-9c71-21a8f6758095.png)

**Comment by gpailler** [comment]
@rashil2000 do you like the new version too? I can create the PR to merge to main.
@mertd Honestly, it's just my personal feeling and maybe ~4200 apps is appealing enough for the first time users 😄. Moreover, as you said, Scoop has other qualities. 

We can keep the official buckets filter on by default and wait to see if we get any feedback from first-time users.

**Comment by rashil2000** [comment]
Yes, looks good to me!
