### ISSUE TITLE
[Bug] TheRandomLabs/scoop-nonportable still listed as an official bucket

### ISSUE THREAD

**Issue by sitiom** [ScoopInstaller/scoopinstaller.github.io#30]
The buckets URL has been updated to point to the new Nonportable bucket in the latest version of Scoop, but the old one is still listed as an official bucket on the site:
![image](https://user-images.githubusercontent.com/56180050/174096213-f461e1a2-d8e6-456e-a974-e13df1e1eb96.png)

When I try to search for apps, the bucket shows up as "undefined" alongside the new Nonportable bucket:
![image](https://user-images.githubusercontent.com/56180050/174096584-5bdb0fbe-6fd5-4ec7-ba68-7b9df82e8bfd.png)

**Comment by gpailler** [comment]
I manually removed *TheRandomLabs/scoop-nonportable* manifests from the index and triggered a new indexing.
*TheRandomLabs/scoop-nonportable* is now listed as a popular bucket.
![image](https://user-images.githubusercontent.com/3621529/174429208-d468a63e-3520-4ea9-962c-ceeab78f8cd6.png)
