### ISSUE TITLE
Possible to have a detail page for apps?

### ISSUE THREAD

**Issue by KyleMit** [ScoopInstaller/scoopinstaller.github.io#47]
If I'm looking to link someone to the app, it'd be helpful to have a route that takes in the app id.

For example, if I search `7zip` like this:

https://scoop.sh/#/apps?s=0&d=1&o=true&q=7zip

I get several results:

![image](https://user-images.githubusercontent.com/4307307/214099899-f3f34ea4-c37c-496d-aa81-ccf5536b5178.png)

But if I want to share the url with someone, they have to decipher which version I meant.

Is it possible to direct link to a specific app?  There are several links in each card to the main website, the licence, the commit, and the release version, but they all take me off the scoop website.  But I couldn't find a way to click to load a single app, similar to how npm handles this:

**Search**: https://www.npmjs.com/search?q=7zip  
**Detail**: https://www.npmjs.com/package/7zip

**Comment by rashil2000** [comment]
A details page doesn't make much sense here, what information will it hold? Especially when the version link will take you to the manifest which contains all information about the package there is.

**Comment by gpailler** [comment]
As @rashil2000 said, we are displaying already as much as we can in the search results. In the NPM example, they have much more info to display like the number of download/issues/dependencies...

But being able to share a link for a specific application could makes sense. I will try to draft something and make a proposal

**Comment by KyleMit** [comment]
That UI looks great, and I really like the deeplink ability. Does the id being used in the URL persist over time?

**Comment by gpailler** [comment]
Yes the id is supposed to be stable. It's a hash of the manifest location in the form : repository + branch + manifest path.

**Comment by KyleMit** [comment]
@gpailler - that looks terrific.  Very intutitive.  Looks great on mobile too

**Comment by gpailler** [comment]
Thanks for the (positive 😊) feedback. It's deployed to https://scoop.sh/
