### ISSUE TITLE
[Bug] Bucket name not displayed correctly

### ISSUE THREAD

**Issue by StarsbySea** [ScoopInstaller/scoopinstaller.github.io#49]
When I use scoop.sh to search for Libreoffice, the web page does not have the correct official Extras name, see the image below
https://scoop.sh/#/apps?q=libreoffice&s=0&d=1&o=false
![Screenshot 2023-02-16 at 16-03-29 Scoop - Apps (libreoffice)](https://user-images.githubusercontent.com/66008060/219304363-cdb39f7f-c55b-4134-bbc4-1e12d67bb34e.png)
If you have time, could you please look at and fix this little problem?

**Comment by rashil2000** [comment]
> https://scoop.sh/#/apps?q=libreoffice&s=0&d=1&o=false

I opened this link and it displays the bucket `extras` correctly to me...

**Comment by StarsbySea** [comment]
After taking a closer look at the network requests, I found the cause. Because my ISP (intermittently) blocks the domain name raw.githubusercontent.com, https://raw.githubusercontent.com/ScoopInstaller/Scoop/master/buckets.json would not load, preventing display the official bucket name correctly.


You can block access to https://raw.githubusercontent.com/ScoopInstaller/Scoop/master/buckets.json的访问就能复现这个问题了 in your browser.

![2023-02-17 091619](https://user-images.githubusercontent.com/66008060/219524554-50b94d54-fc45-412a-86b9-835edd828ab6.png)



In fact, in some regions (e.g. China) raw.githubusercontent.com is a blocked or very difficult domain to access, so can I request to hopefully use jsdelivr's cdn to speed up access to buckets.json?

https://github.com/ScoopInstaller/scoopinstaller.github.io/blob/a40087d0074fd5770cf490a612492724570d3373/src/components/Search.tsx#L152

For example, the above code could be changed to

fetch('https://cdn.jsdelivr.net/gh/ScoopInstaller/Scoop/buckets.json')

Thanks again for your testing and feedback.

**Comment by gpailler** [comment]
Thanks for the investigation and the proposed solution!
I will apply the change

**Comment by StarsbySea** [comment]
Thank you. That solves the problem.
