### ISSUE TITLE
Does the search engine support subdir now?

### ISSUE THREAD

**Issue by niheaven** [ScoopInstaller/scoopinstaller.github.io#50]
https://github.com/ScoopInstaller/Scoop/pull/5119 has been released in v0.3.0, and does this official search engine support it now?

We should restructure official buckets (esp. `extras`) since there're too many manifests now.

**Comment by gpailler** [comment]
I applied a small change in the indexer and manifests in subdirectories are now properly indexed.
I also fixed an encoding issue to support # in manifests paths.

The test repository is properly [indexed](https://scoop.sh/#/apps?q=%22https%3A%2F%2Fgithub.com%2FScoopInstaller%2FTests%22&s=0&d=1&o=false) now so I think subdir are fully supported.
 @niheaven could you take a look? Is there anything else needed?

**Comment by niheaven** [comment]
Wow, thank you, and I think it's enough.

Next step is restructuring current buckets now.
