### ISSUE TITLE
Use navigator.clipboard.writeText() instead of deprecated method

### ISSUE THREAD

**Issue by r15ch13** [ScoopInstaller/scoopinstaller.github.io#51]
Since `document.execCommand('copy')` seems to be deprecated shouldn't it use `navigator.clipboard.writeText()` instead for copying commands?

Could `writeText()` handle the state of the copy button?
```js
navigator.clipboard.writeText(searchValue).then(
  () => {
    // handle effect based on success
  },
  () => {
    // handle effect based on error
  }
);
```

I tried to fiddle around with it but I don't get how exactly data flows in React. (never used it)

**Comment by gpailler** [comment]
Thanks for the info about the deprecated command.
I switched to the new writeText() API and this new version is available on https://scoop.sh/scoopinstaller-dev.github.io but I need to run some extra checks before deploying to https://scoop.sh

Could you give it a try on your side?

**Comment by r15ch13** [comment]
Works great 👍🏽

**Comment by gpailler** [comment]
Deployed to https://scoop.sh. 🚀 
Thanks again
