### ISSUE TITLE
[suggest] add a button for switch contain/not contain  bucket name in install command 

### ISSUE THREAD

**Issue by shishirong** [ScoopInstaller/scoopinstaller.github.io#52]
because bucket can not set order/rank , We have to input bucket name for specify repo.

like this:

want to switch between

```powershell
scoop install xxxx
```

```powershell
scoop install main/xxxx
```

**Comment by StarsbySea** [comment]
Thanks for the suggestion, but I'd like more information before implementing it, for example, do you want only the official bucket to add the bucket name when displaying the install command, or all of them? Assuming the latter, is it the repository name or the bucket alias generated by the site that you want to be displayed?

**Comment by shishirong** [comment]
> Thanks for the suggestion, but I'd like more information before implementing it, for example, do you want only the official bucket to add the bucket name when displaying the install command, or all of them? Assuming the latter, is it the repository name or the bucket alias generated by the site that you want to be displayed?

I want add the bucket name all of them.
I used command is copy from `scoop.sh` website usually when I add scoop bucket, so bucket name is alias generated by the site.
