### ISSUE TITLE
[Bug] Display only official repository function not working properly

### ISSUE THREAD

**Issue by StarsbySea** [ScoopInstaller/scoopinstaller.github.io#53]
When I turn on the official repository only filter, I want to show only the official repository search results

In fact, the web page shows the list files of other community repositories and incorrectly filters the contents of the official extras repository.

Please see the screenshot below for an explanation.

https://scoop.sh/#/apps?s=0&d=1&o=true&p=1&q=v2rayn
![Screenshot 2023-04-11 at 17-13-58 Scoop - Apps (v2rayn)](https://user-images.githubusercontent.com/66008060/231114255-13f816e1-1705-4ed4-8fb5-922584e4caea.png)

https://scoop.sh/#/apps?s=0&d=1&o=false&p=1&q=v2rayn
![Screenshot 2023-04-11 at 17-14-53 Scoop - Apps (v2rayn)](https://user-images.githubusercontent.com/66008060/231114272-62972c5b-e2d2-4f33-a3f9-9cdf2a341d8d.png)

**Comment by gpailler** [comment]
Thanks for the report. There is a bug indeed. I'm working on it

**Comment by gpailler** [comment]
Indexing is fixed and the official buckets switch should work as expected now. 
Could you double check and confirm?

Thanks

**Comment by StarsbySea** [comment]
Problem solve!
![EA6E2C2C-4AD3-4A14-B62C-1D5496E9BA15](https://user-images.githubusercontent.com/66008060/231194211-65d7e295-ea86-42af-8cc6-c571fe84bbf8.jpeg)
