### ISSUE TITLE
Bug: No results found when clicking on a non-official bucket for the first time

### ISSUE THREAD

**Issue by StarsbySea** [ScoopInstaller/scoopinstaller.github.io#55]
### Description of the issue
When a user visits [https://scoop.sh/#/buckets](https://scoop.sh/#/buckets) for the first time and clicks on a non-official bucket, they are redirected to the search page with "No result found" message. The expected behavior should be to display the manifests within the selected non-official bucket.

### Steps to reproduce
1. Visit [https://scoop.sh/#/buckets](https://scoop.sh/#/buckets) for the first time.
2. Click on a non-official bucket.
3. Observe that the search page displays "No result found".

### Possible cause
Upon observation, it seems that the website automatically applies the "Official buckets only" filter. However, I believe this is not the correct behavior. If a user chooses a non-official bucket, they should be able to view the manifests within that bucket.

### Screenshots/GIFs

[video.webm](https://user-images.githubusercontent.com/66008060/233814279-2e54ea95-0c90-410d-bc89-f55f53448f4a.webm)

### Additional context
Please consider updating the filter behavior to allow users to view manifests within the selected non-official buckets. This would improve the user experience and make it easier to navigate the website.

Thank you for your attention to this issue.

**Comment by gpailler** [comment]
Thanks for the extended description. I will take a look to fix it
