### ISSUE TITLE
Include notes in results list

### ISSUE THREAD

**Issue by ltguillaume** [ScoopInstaller/scoopinstaller.github.io#67]
Many buckets have manifests that include important notes that may influence whether you'd want to install the application or not.

Here are 5 significant examples, just by looking at the first 10 manifests of the extras bucket:

> This is a free 30-day trial version. Please buy a copy of it for furthur evaluation.

> Even when you are logging in as 'root', some operations (like service command) require Windows administrator privileges

> AltDrag has not been updated since 2015. It may not work as intended under latest Windows versions.
> We suggest installing 'extras/altsnap', a maintained fork of AltDrag, for better experience.

> This manifest is deprecated and no longer receiving updates. Instead, use the new Android SDK Command-Line tools: `android-clt`.
>- Learn more: https://developer.android.com/tools/releases/sdk-tools

> AntiMicro is no longer being developed, 2.24 is the final release. See this discussion for information: https://github.com/AntiMicro/antimicro/issues/351. AntiMicroX is a fork that is currently supported: https://github.com/AntiMicroX/antimicrox

As such, I think it would be very useful to have these notes included in the results list on scoop.sh

**Comment by rashil2000** [comment]
Hmm, seems like a nice idea. Notes can be hidden by default, and can be shown by clicking an arrow, like this: 

<details>These are the manifest notes.</details>

**Comment by ltguillaume** [comment]
While that would work, I'm not a fan of hiding the info like that: it prevents looking at the info in a single glance while searching through the results for the most likely candidate.

Instead, it might be an idea to allow for two lines to be shown and require the user to expand the notes block if there is more text.

**Comment by gpailler** [comment]
I didn't notice that the `notes` field was carrying this kind of important information. I will definitely take a look to index the notes and propose a way to display them in the search results

**Comment by ltguillaume** [comment]
Great! Thank you so much 😄

**Comment by ltguillaume** [comment]
Small "side question" by the way: are the descriptions not updated with every new version of an application? I saw a strange sequence pop up, namely `something.,Something` (instead of `something. Something`), which is definitely not in the manifest's description field like that.

**Comment by gpailler** [comment]
Thanks for the reminder @ltguillaume ;-) 
- About the commas in the descriptions, it was a nice catch and it's fixed 👍 
- About the notes, it's implemented. If a note field is found in the manifest, it's displayed below the license
