### ISSUE TITLE
Make scoop.sh page's quickstart section copyable and runable

### ISSUE THREAD

**Issue by escape0707** [ScoopInstaller/scoopinstaller.github.io#71]
Right now, there is a `>` symbol prepended the in front of those two lines. It makes it harder to just copy those two lines into the terminal and execute them when one is reinstalling their windows.

**Comment by rashil2000** [comment]
Yes I think we can remove the `>` from those two lines. Could you make a PR?

**Comment by gpailler** [comment]
Fixed by #79
