### ISSUE TITLE
Index for the website has not been updated for 16 days

### ISSUE THREAD

**Issue by garelp** [ScoopInstaller/scoopinstaller.github.io#88]
Hello,
it seems again the index is not updating on the website. :)

regards

**Comment by chawyehsu** [comment]
I just manually triggered the indexer. Please wait and later close this issue when it helps.

**Comment by gpailler** [comment]
Thanks @chawyehsu for the manual run.
I'll keep the issue open until I find a way to not have the workflow automatically disabled after some time for inactivity

**Comment by gpailler** [comment]
I'm using a GitHub action (gautamkrishnar/keepalive-workflow) to keep the workflows alive. It should fix the issue
