### ISSUE TITLE
Update to shim kiennq 3.1.2

### ISSUE THREAD

**Issue by FreeHarry** [ScoopInstaller/scoopinstaller.github.io#93]
Please update to [shim kiennq 3.1.2](https://github.com/kiennq/scoop-better-shimexe). This fixes the bug [Not waiting for an app to finish](https://github.com/kiennq/scoop-better-shimexe/issues/14).

**Comment by gpailler** [comment]
@FreeHarry Wrong repo I guess. You should report this on https://github.com/ScoopInstaller/Scoop instead.
